### ISSUE TITLE
Allow option for sourcemaps

### ISSUE THREAD

**Issue by verydanny** [yibn2008/fast-sass-loader#15]
**what**

Allow ?sourceMaps or option: `{ sourceMaps : true }`

**why**

I realize source maps make performance take a hit, but it's still nice for evaluation, at least allow an option for source maps to be enabled?

**Comment by yibn2008** [comment]
@verydanny fast-sass-loader will pre-merge all sass files to a single file before compiling by node-sass. If sourceMap is enabled, the css code will map to the merged file, not the original sass files, and the map result will be meaningless 

So even if I add sourceMap option, the result won't be what you want

**Comment by davityavryan** [comment]
Hey.
But you can generate your own sourcemap and then pass it. In case if `sourceMap: true` of cource.

**Comment by dmackerman** [comment]
So based on the design of this loader, there's no way for proper source maps to be generated?
