### ISSUE TITLE
Webpack 3 Support

### ISSUE THREAD

**Issue by nikhilmat** [yibn2008/fast-sass-loader#19]
Hello!

Does `fast-sass-loader` support Webpack 3? I have it working correctly in my application, using Webpack 3 and fast-sass-loader 1.2.5.

Would it be possible to add `webpack: 3.x` to the peerDependencies list?

**Comment by yibn2008** [comment]
@nikhilmat  Once I finish webpack 3.x test work, I'll release a new version.

**Comment by yibn2008** [comment]
v1.3.0 released
