### ISSUE TITLE
Support node 8 by upgrade node-sass to 4.5.3

### ISSUE THREAD

**Issue by spiral2k** [yibn2008/fast-sass-loader#21]

**Comment by tryggvigy** [comment]
@spiral2k can you describe this issue?
I'm getting failed builds with `Module build failed: Error: Cannot find module 'node-sass'`. It most definitely is installed. I'm not sure if this issue is related.

**Comment by tryggvigy** [comment]
I can confirm that my fork where I bumped `node-sass` to `4.5.3` fixed my issue. I'm on `node v8.5.0`. I'll make a PR.

**Comment by yibn2008** [comment]
update node-sass semver is unnecessary, just reinstall your node_modules completely will solve your problem.
