### ISSUE TITLE
fast-sass-loader support importer

### ISSUE THREAD

**Issue by rwholey-eb** [yibn2008/fast-sass-loader#22]
i love fast-sass-loader! it's exactly what we needed for our design system with a ton of sass files. We were using sass-loader which exposes an option to set a loader to load different types of files but fast-sass-loader doesn't expose an option for this. 

Specifically we were using sass-loader with a json importer. To get fast-sass-loader to work for us I've written a script to run on a webpack build hook to compile our .json files into .sass files so fast-sass-loader can read them properly. It would be really great if we could encapsulate that behavior into our sass loading process! 

Is this something that fast-sass-loader would be interested in adding? Thanks!

docs for reference https://www.npmjs.com/package/node-sass-json-importer

**Comment by yibn2008** [comment]
@rwholey-eb I have merged PR (it seems you have two github account?), after some test I will release a new version
