### ISSUE TITLE
Trying to get working with babel, raw, and postcss-loaders

### ISSUE THREAD

**Issue by aulneau** [yibn2008/fast-sass-loader#25]
Hi there!

I am very interested in using this in place of `sass-loader`, but unfortunately I'm not able to get it working! I am using this in the context of a next.js project

This is my current configuration:
<img width="620" alt="screen shot 2017-11-04 at 11 51 25 am" src="https://user-images.githubusercontent.com/11803153/32404744-98a539dc-c156-11e7-9925-19e9e91f233c.png">

and when I add in `fast-sass-loader` in place, I get this error:
<img width="592" alt="screen shot 2017-11-04 at 11 53 15 am" src="https://user-images.githubusercontent.com/11803153/32404749-c96ae2c4-c156-11e7-8d44-73c1228ee207.png">

I've tried to debug it, but I am not sure how to proceed!

Thanks so much!

**Comment by yibn2008** [comment]
@aulneau Can you provide a demo project to reproduce it?

**Comment by aulneau** [comment]
Sure!

https://github.com/aulneau/next-sample, just `yarn` and `yarn dev` to run the dev server

So I am using [module resolver](https://github.com/tleunen/babel-plugin-module-resolver) to remove the need to use paths like `../../component.scss` and that seems to be what's causing some of the issues. 

<img width="1358" alt="screen shot 2017-11-06 at 6 20 31 pm" src="https://user-images.githubusercontent.com/11803153/32470728-39397a56-c31f-11e7-929a-7d33baf72152.png">

**Comment by yibn2008** [comment]
the includePaths you pass is like this:

```js
[ '/Users/zoujie.wzj/workbench/next-sample/assets/styles',
  '/Users/zoujie.wzj/workbench/next-sample/node_modules',
  '/Users/zoujie.wzj/workbench/next-sample/components' ]
```

and your import `@import "components/component.scss";` will be resolve to `@import /Users/zoujie.wzj/workbench/next-sample/components/components/component.css`.

Two way to solve this problem:

1. change your `@import "components/component.scss"` to `@import component.scss`
2. or change includePaths to `["./", "node_modules", ...]`
