### ISSUE TITLE
Dedupe not working

### ISSUE THREAD

**Issue by valorize** [yibn2008/fast-sass-loader#26]
I exchanged sass-loader with fast-sass-loader because I need the deduplicating feature of fast-sass-loader.
My config looks like:
```
{
	test: /\.(scss)$/,
	loader: ExtractTextPlugin.extract(
		Object.assign(
			{
				fallback: require.resolve('style-loader'),
				use: [
					{
						loader: require.resolve('css-loader'),
						options: {
							importLoaders: 2,
							minimize: true,
							sourceMap: shouldUseSourceMap,
							modules: true,
							localIdentName: '[local]'
						},
					},
					{
						loader: require.resolve('postcss-loader'),
						options: {
							// Necessary for external CSS imports to work
							// https://github.com/facebookincubator/create-react-app/issues/2677
							ident: 'postcss',
							plugins: () => [
								require('postcss-flexbugs-fixes'),
								autoprefixer({
									browsers: [
										'>1%',
										'last 4 versions',
										'Firefox ESR',
										'not ie < 9', // React doesn't support IE8 anyway
									],
									flexbox: 'no-2009',
								}),
							],
							sourceMap: shouldUseSourceMap,
						},
					},
					{
						loader: require.resolve('fast-sass-loader'),
						options: {
							sourceMap: shouldUseSourceMap,
							precision: 10,
						},
					},
				],
			},
			extractTextPluginOptions
		)
	),
},
```

I then import a library from the javascript index.js like:
import 'infinity/scss/main.scss';
The main.scss itself imports fonts/all.scss which in turn imports icons.scss among others.

In two of my components I import two separate scss files which in turn do `@import "~infinity/scss/fonts/icons";`

First issue: the classes which are imported by `infinity/scss/main.scss` are also included in the scss of the components.
Second issue: the classes which are included by the first component are also included in the second component.

**Comment by ohmirocks** [comment]
Same here dedupe is not working as expected

**Comment by yibn2008** [comment]
@valorize @ohmirocks fast-sass-loader can only dedupe sass files imported by sass file.

For example, the `foobar/index.scss` will be deduped to single one:

```scss
// file: index.scss
@import "foobar/index.scss";
@import "foobar/index.scss";
```

If you import scss files in js code, dedupe won't work:

```js
// file: index.js
import "~foobar/index.scss";
import "~foobar/index.scss";
```

you will get two `foobar/index.scs` in the output.

If you really want dedupe, please import all scss/css files in a single scss file (could be a entry)

---

The reason why fast-sass-loader doesn't support dedupe in scss-in-js is loader in webpack can only process matched file itself, two sass files in one js file will  call fast-sass-loader twice, those two are in different context (they don't know each other)
