### ISSUE TITLE
Options: includePaths is not passed to node-sass

### ISSUE THREAD

**Issue by Root-Core** [yibn2008/fast-sass-loader#27]
Hello there,

I'm porting from grunt to webpack and encountered a problem with the fast-sass-loader.

webpack.config.js
```javascript
        {
          test: /\.(s?css|sass)$/,
          use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
              {
                loader: 'css-loader',
                options: { minimize: true }
              },
              {
                loader: 'fast-sass-loader',
                options: {
                  includePaths: ['client/styles']
                }
              }
            ]
          })
        }
```

The `includePaths` is not passed to the node-sass.
I can verify this by manually added console-loggings in `node_modules/node-sass/lib/index.js`.

**However:** If i am setting `process.env.SASS_PATH = ['client/styles'];` manually, it works fine.
I have not checked other options.

OS: Windows 7 x64 (6.1.7601)
node: v6.11.2
node-sass: 4.7.2
fast-sass-loader: 1.4.0

Regards and keep up your nice work!

**Comment by yibn2008** [comment]
@Root-Core I guess you passed incorrect `includePaths`, this comment may help you: https://github.com/yibn2008/fast-sass-loader/issues/25#issuecomment-342432486

**Comment by Root-Core** [comment]
I think, the given path is okay.
If i pass it via ENV, as you can do with node-sass, it works really well.

It just seems to be not passed to node-sass.

**Comment by yibn2008** [comment]
@Root-Core fast-sass-loader doesn't pass `includePaths` to node-sass, it handle sass import by itself.
