### ISSUE TITLE
Overzealous dedupe

### ISSUE THREAD

**Issue by d4rky-pl** [yibn2008/fast-sass-loader#29]
The deduplication algorithm is also deduping nested imports, resulting in broken/wrong CSS.
<details>
<summary>Full description of the problem</summary>
Let's say we have two SCSS files: `style.scss` which is our main file and `group.scss` which contains a bunch of generic rules. We now want those rules to be imported under a class:

```
.a {
  @import 'group'
}
```

*This will work as expected* and the resulting file will look for ex. like this:

```
.a .c {
  color: red
}
```

Unfortunately if we try to do it in more than one place, the dedupe algorithm will wrongly assume we don't need to import the same file multiple times and silently break our CSS:

```
.a {
  @import 'group'
}

.b {
  @import 'group'
}
```

The above code will result in broken:

```
.a .c {
  color: red
}
/* .b is missing because it didn't contain any rules */
```
</details>

[I've created a repository from above example](https://github.com/d4rky-pl/fast-sass-loader-dedupe-bug). I believe deduping @import should only work if it's in root of the document and not when it's nested.

**Comment by yibn2008** [comment]
en ... I will add a warning for nested imports.
