### ISSUE TITLE
loader doesn't seem to work with Yarn workspaces

### ISSUE THREAD

**Issue by jasonmacdonald** [yibn2008/fast-sass-loader#37]
Just tried switching from sass-loader to fast-sass-loader but all of my imports are causing errors because, I assume, they refer to package `@import "~@lwc-comps/core-styles";` which is a module in my mono-repo. This works fine with sass-loader but here I get the error `Error: import file cannot be resolved: "@import "~@lwc-comps/core-styles";"`. I assume this is because Yarn has lifted all of my package modules to the root `node_modules` folder. Normally, a simple `path.resolve` would find this, but it seems fast-sass-loader isn't using this to resolve paths?

**Comment by yibn2008** [comment]
do you have any example repo to reproduce this?

**Comment by jasonmacdonald** [comment]
I don't have one ready, but let me see if I can put a simple one together that replicates the issue.
