### ISSUE TITLE
Mixing .sass and .scss syntax

### ISSUE THREAD

**Issue by JeffreyWay** [yibn2008/fast-sass-loader#4]
Today, I switched from sass-loader to fast-sass-loader, but noticed an issue related to mixing .sass and .scss files. For example, if I'm compiling `src/app.scss`, and that file has:

```css
@import '_partial.sass';
```

If I run Webpack with your loader, it'll blow up.

```
[1]  .something
     ^
[2]      color: red
[3]
----------------------------------------
Error: Invalid CSS after ".": expected 1 selector or at-rule, was ".something"
    at options.error (/Users/jeffreyway/code/laracasts/node_modules/node-sass/lib/index.js:291:26)
```

Is there any way around this?

**Comment by yibn2008** [comment]
@JeffreyWay `fast-sass-loader` doesn't support mixing .scss and .sass, Please see https://github.com/yibn2008/fast-sass-loader#warning for the reason.

I suggest you convert the .sass file .scss format by [sass-convert](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax)
