### ISSUE TITLE
Unable to load node_modules lib with import

### ISSUE THREAD

**Issue by larsboldt** [yibn2008/fast-sass-loader#40]
Sass loader works when doing @import "~bulma" with following webpack4 config:
`{
        test: /\.(sass|css)$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader'
          }
        ]
      },`

fast-sass-loader does not, switching out sass-loader with fast-sass-loader ends up with fast-sass-loader not being able to resolve ~bulma.

Bug or am I missing some config? I've tried added options includePaths with path.resolve('node_modules') but still same result in fast-sass-loader.

**Comment by yibn2008** [comment]
what's the error info?

**Comment by larsboldt** [comment]
ERROR in ./build/modules.sass (./node_modules/css-loader!./node_modules/fast-sass-loader/lib!./build/modules.sass)
Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
Error: File to import not found or unreadable: ~bulma.
    at options.error (/path/to/project/node_modules/node-sass/lib/index.js:291:26)
 @ ./build/modules.sass 2:14-123
 @ ./build/modules.js

**Comment by pablote** [comment]
same issue here, found a fix/workaround?

**Comment by yibn2008** [comment]
try fast-sass-loader@1.4.7, this issue should be fixed.

Notice: DO NOT mixing import .scss and .sass file at same file, fast-sass-loader doesn't support. `@import "~bulma"` will be resolved to `@import "~bulma/bulma.sass"`, so the file you import bulma should also be .sass file.

**Comment by j1wilmot** [comment]
@yibn2008 I'm still seeing this issue with 1.4.7. I've created a sample project to demonstrate: https://github.com/j1wilmot/fast-sass-loader-test

The sample project tries to import a scss file from a node module and generates the same kind of "File to import not found" error as mentioned above. Any thoughts?

**Comment by de3web** [comment]
@j1wilmot Nice catch identifying the file being loaded initially from a .js file.

**Version**: 1.4.7
**Webpack**: 4.20

I'm also experiencing the same issue with a file structure of:

**index.js**
```
import './global/style/app.scss';
```

**app.scss** (where it's failing)
```
@import "functions/**/*.scss";
```

**Comment by yibn2008** [comment]
@j1wilmot you should add a `;` after `@import `@import "~bootstrap/scss/alert.scss"`

**Comment by hallya** [comment]
same probleme here. I'm using alias defined in webpack config to import specifics `.scss` file.

```
Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
Error: import file cannot be resolved: "@import 'styles/_variables';" @/Users/user/foo/src/some/path/styles.m.scss
    at Object.importReplacer (/Users/user/foo/node_modules/fast-sass-loader/lib/index.js:207:19)
    at importReplacer.throw (<anonymous>)
    at onRejected (/Users/user/foo/node_modules/co/index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ ./src/some/other/path/styles.m.scss 2:26-173 43:4-64:5 46:18-165
 @ ./src/some/other/path/index.jsx
 @ ./src/some/path/index.jsx
 @ ./src/routes/general.jsx
 @ ./src/routes/index.jsx
 @ ./src/Root.jsx
 @ ./src/index.jsx
```
