### ISSUE TITLE
Allow some sass options to be set, i.e. precision

### ISSUE THREAD

**Issue by atsolberg** [yibn2008/fast-sass-loader#41]
Currently there is no way to set the `precision` option like you would with `sass-loader`.  A lot of projects using bootstrap will experience some measurements being off by 1px because the default line-height has 9 precision digits. node-sass defaults to 5 precision digits.

Example: 14px font-size * 1.428571429 line-height would end up as 20px but 14px font-size * 1.42857 line-height would be 19px.

**Comment by yibn2008** [comment]
I have no plan for this feature, any PR will be welcome.
