### ISSUE TITLE
js file picked up instead of css

### ISSUE THREAD

**Issue by juamei** [yibn2008/fast-sass-loader#46]
In the latest release the addition of this code into index.js
```
  // is module import
  if (original.startsWith('~') && (dirname === '.' || dirname.indexOf('/') < 0)) {
    return [original]
  }
```
has meant that the code is now including a javascript file instead of a css file, seemingly when an npm package doesnt fit into the right dir format.
The scss line is 
`@import "~spectrum-colorpicker/spectrum";`

That npm package has two files in its route; spectrum.js and spectrum.css. You are now picking up spectrum.js and collating it into the main css file. Which obviously then breaks. 

Apologies this isnt a proper test case, this is buried deep in some project code. I can probably knock one together but it'll take me a while.

**Comment by flaviotulino** [comment]
I have exactly the same issue too trying to import "spectrum"

**Comment by DanielRuf** [comment]
Hm, why not reference the .css file (be more explicit)? I do the same with other projects. The extensionless way is not good at all - ond of the things which Ryan Dahl - the creator of Node.js - regrets.

**Comment by yibn2008** [comment]
As @DanielRuf said, just import with .css extension.
