### ISSUE TITLE
Issue with relative imports and aliases

### ISSUE THREAD

**Issue by emikoshi** [yibn2008/fast-sass-loader#47]
Hi there,

It seems upgrading from 1.4.6 to 1.4.7 has created an issue with a case of importing. Though I am not sure if this has to do with not ideal practices on my part or an oversight with 1.4.7

Currently throughout our project some imports in scss files are done such as:
`@import '~scss/meta';`

Though an alias exists for part of the path in the webpack.config.js, such as:
`resolve: {
	alias: {
            scss:  path.resolve(__dirname, PATH_TO_SHARE, "source/scss/")
         }
 }`

So with 1.4.7 installed, I'm getting errors throughout our SCSS files: 
`Error: import file cannot be resolved: "@import '~scss/meta';"`

Removing the `~` seems to get rid of the import errors associated, fwiw.

Any insight would be greatly appreciated!

**Comment by yibn2008** [comment]
If you using `@import '~scss/meta'` to import relative sass file, it's incorrect. Because `~` means a module in webpack
