### ISSUE TITLE
Actually 0.2 - 0.5 seconds slower in my case

### ISSUE THREAD

**Issue by DanielRuf** [yibn2008/fast-sass-loader#49]
It seems this loader does not produce much faster builds in the current webpack 4 version.

https://travis-ci.com/DanielRuf/sass-loader-benchmark/jobs/180129808#L506
https://travis-ci.com/DanielRuf/sass-loader-benchmark/jobs/180129809#L506

https://travis-ci.com/DanielRuf/sass-loader-benchmark/jobs/180129171#L506
https://travis-ci.com/DanielRuf/sass-loader-benchmark/jobs/180129172#L506

In fact there is only an advantage when someone falsely reimports files instead of importing them at the root or proper level. So I guess this is not an option for us.

**Comment by yibn2008** [comment]
Since fast-sass-loader optimizing building speed by deduping sass files, if your project has no duplicate sass files, just use sass-loader directly.
