### ISSUE TITLE
vue 文件 多个style 模块 缓存问题

### ISSUE THREAD

**Issue by nailfar** [yibn2008/fast-sass-loader#52]
vue 文件 多个style 模块 缓存问题
```
let entry = this.resourcePath
let cache = new Cache(entry)
```
 以文件路径作为缓存的标识符  无法满足 当vue 单文件中出现 多个<style lang=“scss”>...</style>模块后，vue-loader 会调用多次 fast-sass-loader   但是文件路径还是同一个 命中缓存后 会取第一个<style>代码块的代码

**Comment by yibn2008** [comment]
这个无法做到, fast-sass-loader 只支持一个 scss 入口下的文件去重, 这个是 webpack 的底层实现决定的.

**Comment by nailfar** [comment]
我觉得可以抢救一下  可以缓存策略上优化下  除了文件路径还有路径参数可以用来区分是不是同一个内容块

**Comment by yibn2008** [comment]
@nailfar 你如果有思路, 可以提个 PR :-)
