### ISSUE TITLE
Passing outputStyle to sass.render

### ISSUE THREAD

**Issue by bd041556** [yibn2008/fast-sass-loader#53]
We have successfully replaced sass-loader with fast-sass-loader, and are seeing very nice performance improvements. However, our output files are substantially larger. We have traced that to the fact that our rule for sass-loader sets use.options.outputStyle to "compressed"in our webpack configuration file, and we have many comments in our .scss files which outputStyle "compressed" eliminates. 

Currently, I don't see a way to pass an outputStyle through fast-sass-loader to node-sass, so we experimented by hacking index.js to do that:

      try {
        let result = yield new Promise((resolve, reject) => {
          sass.render({
            indentedSyntax: entry.endsWith('.sass'),
            outputStyle: 'compressed',
            file: entry,
            data: merged
          }, (err, result) => {
            if (err) {
              reject(err)
            } else {
              resolve(result)
            }
          })
        })

and that worked for us. Can outputStyle be added to the fast-sass-loader options?
We can work up a PR if you would like.

Thanks,
Barry Bentley

**Comment by yibn2008** [comment]
It's OK for me, PR will be welcome :-)

**Comment by bd041556** [comment]
A PR has been created. The source code changes are very simple. The README has been updated, and a test case (pass-output-style) has been created.

**Comment by yibn2008** [comment]
+fast-sass-loader@1.5.0
