### ISSUE TITLE
resolve-url url() to absolute path

### ISSUE THREAD

**Issue by KevinKP17** [yibn2008/fast-sass-loader#58]
# Problem
our file structure separates the assets and scss files (not in one directory)
fas-sass-loader always try to fill the assets location same as scss files where the assets are called.
is there a way to turn these off and point the `url()` to designated location??

# Code Snippet
### Error log
```
ERROR in ./app/stylesheets/packs/mobile/home.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../../gulp/assets/stylesheets/mobile/icons/icn-upload.png' in '/vidio_vagrant/app/stylesheets/packs/mobile'
```

### gulp/assets/stylesheets/mobile/upload.scss
```background-image: image-url("icon/icn-upload.png")```

### gulp/assets/stylesheets/mixin/images.scss
you can see that i tried to input the url
```@function image-url($url) { @return url("app/assets" + $url); }```

### app/assets/icon/icn-upload.png
assets are located in here!!

Please is there any kind of config?
so that i can change using my path

Thanks

**Comment by yibn2008** [comment]
since fast-sass-loader support url-resolve, dynamic url() rule is conflict with url resolve logic, you can use original sass-loader to solve this problem.
