### ISSUE TITLE
Does fast-sass-loader intend to sync options with sass-loader?

### ISSUE THREAD

**Issue by qodesmith** [yibn2008/fast-sass-loader#61]
`sass-loader` has published version 8 and they have [breaking changes](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#800-2019-08-29) to their options config. They now put the options under the `sassOptions` property. I'm just curious if it's the intention of this library to keep that option structure in sync. Regardless, I love using `fast-sass-loader`! Thank you folks for all your hard work!

**Comment by yibn2008** [comment]
Currently I don't think it is necessary to sync options with sass-loader, thanks~
