### ISSUE TITLE
@use not working in scss

### ISSUE THREAD

**Issue by RacerDelux** [yibn2008/fast-sass-loader#67]
Pretty straight forward issue. I have a global.scss that at the very top has this code:
`@use "~material-components-web/material-components-web";`
If I run it like that, it fails with this message:
![image](https://user-images.githubusercontent.com/2667344/109020166-55f55e00-767f-11eb-8d5c-55d2a5d3deac.png)
If I use import instead like:
`@import "~material-components-web/material-components-web.scss";`
It fails with the following message:
![image](https://user-images.githubusercontent.com/2667344/109020268-70c7d280-767f-11eb-8cbc-7c6e4bf6f452.png)
Note at this point it is failing to include the dependency chain within material's codebase. This is outside of my code.

**Comment by andreyvolokitin** [comment]
I guess migration to `dart-sass` is required, AFAIK `node-sass` doesn't support `@use` (as well as being deprecated)

**Comment by yibn2008** [comment]
already fixed in the latest release
