### ISSUE TITLE
How to add resolve paths (webpack 2)

### ISSUE THREAD

**Issue by elfleat** [yibn2008/fast-sass-loader#7]
What would be the equivalent with fast-sass-loader than the includePaths option in sass-loader?
```javascript
{
    loader: 'sass-loader',
    options: {
        sourceMap: settings['source-maps'],
        includePaths: [bourbon, neat]
    }
}
```

**Comment by micahcatlin** [comment]
I would value this feature as well.

In its absence, I have had to modify all of my .scss source files to @import other files with relative paths (instead of absolute paths starting at my desired includePath root).

**Comment by yibn2008** [comment]
@elfleat @micahcatlin now *fast-sass-loader@1.2.1* support `includePaths`, you can try it
