### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by faddee** [yibn2008/fast-sass-loader#8]
I get `Module build failed: TypeError: Cannot read property 'config' of null` with v1.2.1. Seems like it occurs when you don't pass any query at all. Fixed by replace [this line](https://github.com/yibn2008/fast-sass-loader/commit/44e60bd388fed889831a4207e5725817ea138c91#diff-6d186b954a58d5bb740f73d84fe39073R47) with:

```js
let query = loaderUtils.getOptions(loaderContext) || {}
```

**Comment by yibn2008** [comment]
@faddee This issue has been fixed, you can upgrade to 1.2.2
