### ISSUE TITLE
includePaths do not work as expected

### ISSUE THREAD

**Issue by weaintplastic** [yibn2008/fast-sass-loader#9]
When working with the includePaths options I encounter some issues.

Let's say I'd like to use the styles of a library loaded via npm dependency. I'd write an import statement like this, knowing that ther is a file located in `node_modules/super-duper-library/_index.scss`;

```
@import 'super-duper-library/index';
```
To make this work with node-sass, I'd add `node_modules` as an includePath.

```
includePaths: ['./node_modules']
```

Somehow the concept of includePaths of your library is different. I couldn't figure out the idea behind it by just looking at the code. Anyways, I'll create a pull request, that's solving this issue. Looking forward to get your opinion on this.

**Comment by yibn2008** [comment]
@weaintplastic if you want require scss file from external modules under `node_modules` dir, you should use:

```scss
@import "~some-package/entry.scss";
```

instead of using `includePaths`.

Currently, `includePaths` in fast-sass-loader expect to be a absolute path, the behavior of relative path has not been considered yet.

**Comment by weaintplastic** [comment]
@yibn2008 thanks so much for the fast reply. 

Since I'm working on a modular system where the user can decide which modules to use and how to compile them, I just don't like to rely on the way webpack is loading resources from node_modules using `~` which is not compatible with how you'd deal with it using node-sass/libsass. 

Also if fast-sass-loader is meant to be a replacement for sass-loader, then I'd expect it to handle includePaths the same way?

**Comment by yibn2008** [comment]
@weaintplastic According to documents about `SASS_PATH`, the `includePaths` (which will pass to libsass as `SASS_PATH` env variable) is just a list of search path for `@import` statement. So the current logic of fast-sass-loader is correct and works as expectation.

Related docs:

- https://github.com/customink/sass_paths#directories
- http://chriseppstein.github.io/blog/2012/08/23/sass-3-2-is-released/
- https://github.com/sass/libsass/issues/90
- https://github.com/webpack-contrib/sass-loader#examples

They are all expect includePaths to be *absolute* path. So just change your `./node_modules` to absolute path, the result should work as you expect.
